version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: gesture_auth_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword
      - MONGO_INITDB_DATABASE=gesture_auth
    networks:
      - app_network
    restart: unless-stopped

  # Machine learning client service
  ml-client:
    build: ./machine-learning-client
    container_name: gesture_ml_client
    depends_on:
      - mongodb
    ports:
      - "5050:5050"
    volumes:
      - ./machine-learning-client:/app
    environment:
      - MONGODB_URI=mongodb://admin:secretpassword@mongodb:27017/gesture_auth?authSource=admin
    networks:
      - app_network
    restart: unless-stopped

  # Web app service
  web-app:
    build: ./web-app
    container_name: gesture_web_app
    ports:
      - "5055:5001"
    depends_on:
      - mongodb
      - ml-client
    volumes:
      - ./web-app:/app
    environment:
      - MONGODB_URI=mongodb://admin:secretpassword@mongodb:27017/gesture_auth?authSource=admin
      - FLASK_ENV=development
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge