name: Web App CI

on:
  push:
    paths:
      - 'machine-learning-client/**'
  pull_request:
    paths:
      - 'machine-learning-client/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
          docker build -t ml-client-test ./machine-learning-client
    
    - name: Run web-app tests
      working-directory: machine-learning-client
      run: pytest tests/